services:
  api:
    image: jodogne/orthanc 
    ports:
      - "8042:8042"
    networks:
      - mynetwork

  app:
    image: analise-imagens-medicas
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
