version: '3'
services:
  api:
    image: jodogne/orthanc 
    ports:
      - "8042:8042"
    networks:
      - mynetwork

  app:
    image: rafael-dosso-miclab
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
